version: "3"

services:
  nginx:
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: $SERVER_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./sources:$PHP_USER_HOME_DIRECTORY
    ports:
      - $SERVER_PORT:80

  php:
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./sources:$PHP_USER_HOME_DIRECTORY

  mariadb:
    build:
      context: docker/mariadb
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MARIADB_USER: $DATABASE_USER
      MARIADB_PASSWORD: $DATABASE_PASSWORD
      MARIADB_DATABASE: $DATABASE_NAME
    volumes:
      - ./database:/var/lib/mysql
